const $=id=>document.getElementById(id);let market='Shopee',running=false,products=[];
const defs=[['item_id','Item ID','ID unik produk'],['shop_id','Shop ID','ID toko'],['name','Nama Produk','Judul produk'],['price','Harga','Harga aktif'],['discount_price','Harga Diskon','Harga sebelum/sesudah diskon'],['stock_status','Status / Stok','Status ketersediaan'],['rating','Rating','Rating produk'],['sold','Terjual','Jumlah terjual'],['image_main','Gambar Utama','Foto utama produk'],['images','Semua Gambar','Galeri produk saja'],['url','URL Produk','Link detail produk'],['category','Kategori','Kategori produk'],['variations','Variasi','Nama + opsi variasi'],['scraped_at','Waktu Scrape','Waktu pengambilan'],['marketplace','Marketplace','Shopee / Tokopedia']];
let selected=new Set(defs.map(x=>x[0]));
function safe(id){return $(id)}
function line(x){const l=$('log');if(!l)return;l.textContent+=`\n[${x.time}] ${String(x.type||'INFO').padEnd(7)} ${x.msg}`;l.scrollTop=l.scrollHeight}
window.scard.onLog(line);
window.scard.onProgress(x=>{safe('fraction').textContent=`${x.done} / ${x.total}`;safe('bar').style.width=`${x.total?x.done/x.total*100:0}%`});
window.scard.onSummary(s=>{safe('ok').textContent=s.ok;safe('fail').textContent=s.fail;safe('partial').textContent=s.partial});
window.scard.onProduct(x=>{let r=x.row||{};safe('curNo').textContent=`${x.index} / ${x.total}`;safe('pstatus').textContent=x.status;safe('pname').textContent=r.name||'Membaca produk...';safe('pprice').textContent=r.price!=null?'Rp '+Number(r.price).toLocaleString('id-ID'):'-';safe('prating').textContent=r.rating??'-';safe('psold').textContent=r.sold??'-';safe('pstock').textContent=r.stock_status||'-';safe('pimages').textContent=(r.images||[]).length+' foto';if(r.image_main)safe('pimg').src=r.image_main;
 safe('checks').innerHTML=[['Nama',r.name],['Harga',r.price],['Gambar',r.image_main],['Rating',r.rating],['Terjual',r.sold],['URL',r.url]].map(([a,b])=>`<div class="${b!==null&&b!==''&&b!==undefined?'yes':''}">${b!==null&&b!==''&&b!==undefined?'✓':'○'} ${a}</div>`).join('');if(x.status==='SUCCESS'||x.status==='PARTIAL'){products[x.index-1]=r;renderStrip()}});
function renderStrip(){safe('strip').innerHTML=products.filter(Boolean).map(r=>`<div class="mini"><img src="${r.image_main||''}"><small>${escapeHtml(r.name||'Produk')}</small><small>${r.price!=null?'Rp '+Number(r.price).toLocaleString('id-ID'):''}</small></div>`).join('')||'<div class="emptyStrip">Produk yang selesai akan muncul di sini.</div>'}
function escapeHtml(v){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function cstatus(){try{let s=await window.scard.chromeStatus(market);safe('chromeState').textContent=s.ready?'● Chrome Siap — tetap buka':'● Chrome belum terhubung';safe('chromeState').classList.toggle('off',!s.ready)}catch(e){safe('chromeState').textContent='● Status Chrome gagal dibaca'}}
function chooseMarket(name){market=name;document.querySelectorAll('.platform button').forEach(x=>x.classList.toggle('on',x.dataset.m===name));cstatus()}
document.querySelectorAll('.platform button').forEach(b=>b.addEventListener('click',()=>chooseMarket(b.dataset.m)));
safe('chrome').addEventListener('click',async()=>{try{await window.scard.openChrome(market);line({time:new Date().toLocaleTimeString('id-ID'),type:'INFO',msg:`Chrome ${market} dibuka. Login/verifikasi lalu biarkan tetap terbuka.`});setTimeout(cstatus,1500)}catch(e){alert(e.message)}});
safe('run').addEventListener('click',async()=>{if(running){window.scard.stop();safe('run').textContent='Menghentikan…';return}if(!selected.size){alert('Pilih minimal satu data untuk export.');return}running=true;safe('run').textContent='■ STOP';safe('ready').textContent='● Running';products=[];renderStrip();safe('log').textContent='SCARD Engine v15 starting...';try{await window.scard.start({market,url:safe('url').value.trim(),limit:safe('limit').value,fields:[...selected]});safe('ready').textContent='● Selesai'}catch(e){line({time:new Date().toLocaleTimeString('id-ID'),type:'ERROR',msg:String(e.message||e).replace(/^Error invoking remote method '[^']+': Error:\s*/,'')});safe('ready').textContent='● Error'}finally{running=false;safe('run').textContent='▶ START'}});
safe('copy').addEventListener('click',async()=>{await navigator.clipboard.writeText(safe('log').textContent);safe('copy').textContent='COPIED ✓';setTimeout(()=>safe('copy').textContent='COPY LOG',1000)});safe('clear').addEventListener('click',()=>safe('log').textContent='Log dibersihkan.');
safe('json').addEventListener('click',()=>window.scard.saveJSON().catch(e=>alert(e.message)));safe('excel').addEventListener('click',()=>window.scard.saveExcel().catch(e=>alert(e.message)));safe('upload').addEventListener('click',()=>window.scard.upload().then(()=>alert('Berhasil dikirim ke cPanel')).catch(e=>alert(e.message)));
async function settings(){let s=await window.scard.settingsGet();safe('endpoint').value=s.endpoint||'';safe('token').value=s.token||'';safe('setdlg').showModal()}safe('settings').addEventListener('click',settings);safe('save').addEventListener('click',async()=>{await window.scard.settingsSet({endpoint:safe('endpoint').value.trim(),token:safe('token').value});safe('setdlg').close()});safe('test').addEventListener('click',()=>window.scard.apiTest({endpoint:safe('endpoint').value.trim(),token:safe('token').value}).then(()=>safe('testmsg').textContent='✓ Connection OK').catch(e=>safe('testmsg').textContent='✕ '+e.message));safe('docs').addEventListener('click',()=>safe('docdlg').showModal());
function drawFields(){safe('fieldGrid').innerHTML=defs.map(([k,n,d])=>`<label class="fieldItem"><input type="checkbox" data-field="${k}" ${selected.has(k)?'checked':''}><span><b>${n}</b><small>${d}</small></span></label>`).join('');safe('fieldCount').textContent=`${selected.size} / ${defs.length} dipilih`;safe('selectAll').checked=selected.size===defs.length;safe('fieldsBtn').textContent=`☑ Pilih Data (${selected.size}/${defs.length})`;safe('selectAll').indeterminate=selected.size>0&&selected.size<defs.length;safe('fieldGrid').querySelectorAll('input').forEach(i=>i.addEventListener('change',()=>{i.checked?selected.add(i.dataset.field):selected.delete(i.dataset.field);drawFields()}))}
safe('fieldsBtn').addEventListener('click',()=>{drawFields();safe('fielddlg').showModal()});safe('selectAll').addEventListener('change',e=>{selected=e.target.checked?new Set(defs.map(x=>x[0])):new Set();drawFields()});safe('closeFields').addEventListener('click',()=>safe('fielddlg').close());
cstatus();setInterval(cstatus,5000);